# Upstream changes from _extends are only recognized when modifications are made to this file in the default branch.
_extends: .github
repository:
  name: terraform-spacelift-cloud-infrastructure-automation
  description: Terraform module to provision Spacelift resources for cloud infrastructure automation
  homepage: https://cloudposse.com/accelerate
  topics: ""

