projects:
  globals:
    stage: testing
    environment: uw2

  terraform:
    example2:
      workspace_enabled: true
      vars:
        my_input_var: "Hello world! This is example1. It's disabled!"
    example3:
      workspace_enabled: true
      triggers:
        - gbl-root-example1
      vars:
        my_input_var: "Hello world! This is example2. This project contains a custom trigger!"
